services:
  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    networks:
      - production-network
    volumes:
      - ~/redis/data:/data
    command: ["redis-server", "--appendonly", "yes"]

networks:
  production-network:
    external: true
